apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: rdspostgresql-test-goldin
spec:
  forProvider:
    region: us-west-2
    dbInstanceClass: db.t2.small
    masterUsername: masteruser
    allocatedStorage: 10
    engine: postgres
    engineVersion: "12"
    skipFinalSnapshotBeforeDeletion: true
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: aws-rdspostgresql-conn
